language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly-8.0

install:
  - composer self-update
  - composer install --dev

script: composer test

matrix:
  allow_failures:
    - php: nightly-8.0
  fast_finish: true